const LAST_TIER = 4;
const COURSE_FINISHED_TIER = 5;
const COURSE_FINISHED_LESSON_NUMBER = 100;
const PW_SALT_ROUNDS = 12;

module.exports = {
  LAST_TIER,
  COURSE_FINISHED_TIER,
  COURSE_FINISHED_LESSON_NUMBER,
  PW_SALT_ROUNDS,
};
